### ISSUE TITLE
Mig-21

### ISSUE THREAD

**Issue by Hovra** [Frosties82/RedSands#19]
Set radio FRQ for Mig-21. Mig-21 has only preset channels that need to be set to get in contact with ATC/MAGIC/etc.

**Comment by thebgpikester** [comment]
Hey!
We are doing a revamp on all aircraft for all frequencies and supplying a Mission Data Card for the mission in one big move asap, in order to consolidate and simplify the experience. Mig-21 is definitely on the cards.
Most likely will come with the next update which isn't quite in testing yet, so hang in there!

**Comment by thebgpikester** [comment]
Done. Also Mig-21 moved to red only to keep the consistency of the mission with the realistic sides and orbats as per our design.
